pact-foundation/pact-js

src/pact.js
This fixes a regression in pact 2.x where the pact-node CORS option was no longer exposed
=> Pass cors option to pact-node

README.md
I think this is correct, it matches all the examples in the ./examples folder of this repository
=> Fixes 'provider.verify()' call in example

README.md
The example Pact test in the README contains a test anti-pattern. The call to `provider.verify` is in a seperate test to the code that actually makes the http request that is verified. This leads to brittle tests as a change in the order of test execution will cause the test to fail. For example, jasmine has a flag that will cause it to execute tests in a random order.
=> core(docs): remove anti-pattern from example in readme

config/webpack.web.config.js, examples/e2e/test/consumer.spec.js, src/common/net.js, src/pact.js, test/common/net.spec.js
Fast fail a build during `setup()` if the port is taken by another process.
Results in a test failure similar to the below in the E2E [Mocha](https://github.com/pact-foundation/pact-js/blob/feat/port-check/examples/e2e/test/consumer.spec.js) test:
```shell
> e2e@1.0.0 test:consumer /Users/mfellows/development/public/pact-js/examples/e2e
> mocha test/consumer.spec.js
Pact
1) "before all" hook
2) "after all" hook
0 passing (35ms)
2 failing
1) Pact "before all" hook:
Error: Unable to start the Pact Server: Error: Port 1234 is unavailable
at provider.setup.then.then.then.catch.e (test/consumer.spec.js:140:15)
at process._tickCallback (internal/process/next_tick.js:103:7)
```
Fixes #37
=> feat(port-check): check if port is available during setup() #37

README.md, examples/e2e/test/provider.spec.js
Adds support for a new feature of the broker - the ability to send provider verification results back to the Broker, allowing more intelligent CI practices.
The main use case this solves is allowing you (probably via a CI / CD processe) to detect Consumer changes that have not yet been verified by a provider. Publishing the status to the broker allows tooling to then query this status, and block a deployment if the contract has changed or has not been verified since last published.
See https://github.com/realestate-com-au/pact/blob/master/CHANGELOG.md#1110-8-may-2017 for background.
Waiting for https://github.com/pact-foundation/pact-node/pull/35 before merging.
=> feat(verifications): update example to publish verification results

src/dsl/mockService.d.ts, src/dsl/mockService.js, src/pact-web.d.ts, src/pact-web.js, src/pact.d.ts, src/pact.js
I want to use the [pactfile_write_mode feature](https://github.com/realestate-com-au/pact/blob/master/documentation/configuration.md#pactfile_write_mode) for separated test files.
=> feat(mock service): add pactfile_write_mode option handling

README.md
Putting a `like` around each value is tedious. The documentation needs to show that the like can be wrapped around the entire object.
=> Updated documentation around like and eachLike

README.md
* Removing unused `request` library being required
* The port constant was not defined
* Cosmetic change from `let` to `const`
=> docs(README): updating example

README.md
Fix #65 by asserting that the promise for `provider.verify()` hasn't thrown an error, thus providing a clearer example of usage for it.
=> docs(readme): improved example for asserting expectations on contract

src/common/logger.js, src/dsl/mockService.d.ts, src/dsl/mockService.js, src/pact-web.js, test/common/logger.spec.js, test/dsl/mockService.spec.js
See https://github.com/pact-foundation/karma-pact/pull/4#issuecomment-330108787 and https://github.com/pact-foundation/pact-js/issues/59#issuecomment-330183133 for background.
- For pact-web use cases, where mock service is started
independently of the test cases themselves, we allow
consumer and provider to be specified in underlying
mock service directly.
- Logs warning to console if details aren't provided to
assist in debugging issues
- Addresses pact-foundation/karma-pact/pull/4
- Addresses #59
=> feat(karma): relax consumer/provider requirement in MockService

src/dsl/matchers.js
fix a typo in eachLike DSL matcher were comparison to < 1 would cause an error but error message
said > 1 which is incorrect
=> fix(src): fix typo in error message

src/pact.js
When running pact tests (that also start the pact mock server) and the application code (that calls the APIs defined in the pact interactions) on different servers (or different docker containers), the pact server should be binded to a different host other than localhost, otherwise the API calls in the application won't reach the mock server.
pact constructor in src/pact.js already get a "host" option but it is not passed to serviceFactory.createServer() method.
=> feat(pact-server): allow to run pact mock server on a host other than localhost

src/pact-web.js, test/dsl/integration.spec.js
Verification error message is now passed on instead of being swallowed.
I'm not sure if it has any side effects, but at least for my use case (through karma-pact) this change made the experience of writing consumer tests much more pleasant, since I can now see what went wrong in the karma results in the browser.
fixes #113
=> fix(verification): pass validation error message on 

scripts/build.sh
I noticed we're not checking the actual examples code to make sure they pass and actually work so I updated the build script which is used for the e2e examples.
=> build(travis): make sure we test all examples code

package.json
`es6-promise` is used in the verifier, and thus needs to be a dependency of this package so
consumers can pickup the type definition.
I can confirm this fixes #142 regarding `es6-promise`. `bunyan` is missing from `pact-node` but I'll look at raising that separately.
=> fix(typescript) promotes es6-promise to a dependency as it's publically exposed

README.md, examples/typescript/index.ts, examples/typescript/package.json, examples/typescript/test/get-dog.spec.ts, examples/typescript/test/helper.ts, examples/typescript/test/mocha.opts, examples/typescript/tsconfig.json, examples/typescript/tslint.json, package.json, src/dsl/interaction.ts, src/pact.spec.ts, src/pact.ts
Cleans up the Type interface for TS usage, in a backwards-compatible way:
- `pact.addInteraction()` now accepts union type InteractionObject | Interaction
- Builder pattern as first-class citizen (exported as Interaction)
- Add TypeScript example demonstrating both builder and literal examples
=> Allow TS builder interface to work with literal interface

README.md
I think having this in the first example on the page would have cleared up a lot of problems from the start. An issue with me was going in quick running 'npm install pact-js' which would have put `pact` in my modules.
After installing the v5 @pact-foundation/pact I think my code references must have still been hitting v4.
=> Require '@pact-foundation/pact' in inline example

README.md
The example shows "like" being imported from 'pact'; it should be imported from "Matchers"
=> Fix import in example

examples/e2e/test/provider.spec.js
It appears that pact-node allows specifying local (file, or directory path) or remote (url) locations of pact files under the `pactUrls` key.
When playing around with the e2e example, uncommenting the relevant lines (using them as an example) resulted in errors. (See my comment on pact-foundation/pact-node/issues/78, for details regarding my setup, and the exact error)
Updating the example keys to `pactUrls` resolved issues for me.
As this updates commented-out code, I couldn't figure out a quick & graceful way of `testing` it (other than manual checks). I notice that [pact-foundation/pact-node/blob/master/src/verifier.spec.ts](https://github.com/pact-foundation/pact-node/blob/master/src/verifier.spec.ts) includes some examples using `pactUrls`.
=> e2e example: Update keys for setting local/remote pact files in verifyProvider opts

package.json, src/common/logger.ts
The package.json file appears at a different relative location in the source tree versus the compiled package.
It should be resolved regardless of the level of nesting present in the calling module.
Relates to https://github.com/pact-foundation/pact-js/issues/173
=> fix: Resolve package.json for version metadata regardless of nesting

src/dsl/interaction.spec.ts, src/dsl/interaction.ts
Fixes #177 
The problem existed only for response bodies, but I also added tests for request bodies so as to prevent a regression.
=> fix(interaction): include response body if set to empty string

examples/jest/README.md
This would have saved me some time getting the example to work. Without the first two steps, I was getting this error:
```
bash> npm t
> jest@1.0.0 test /Users/chris/projects/other/pact-js/examples/jest
> jest __tests__/ --runInBand --setupFiles ./pactSetup.js --setupTestFrameworkScriptFile ./pactTestWrapper.js
FAIL  __tests__/another.spec.js
● Test suite failed to run
Cannot find module '../../dist/pact' from 'pactSetup.js'
at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
at Object.<anonymous> (pactSetup.js:2:12)
FAIL  __tests__/index.spec.js
● Test suite failed to run
Cannot find module '../../dist/pact' from 'pactSetup.js'
at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
at Object.<anonymous> (pactSetup.js:2:12)
Test Suites: 2 …
```
=> chore(docs): update directions in jest example readme

src/messageProviderPact.ts
When running MessageProvider tests using Jest the test pack never quits. This has been narrowed down to a http server that is started when calling the verify() method but is never closed. A small
change to ensure that the server gets shut down correctly after the verification has been completed.
=> close http server instance started by Message Provider Verifier

src/pact.spec.ts, src/pact.ts
All successful/failed calls to pact.verify() should clear
interactions so that subsequent tests don't det out of whack.
NOTE: Promise.finally() would have been nicer, note for
upgrade to latest TS in next major release.
Fixes #231
=> fix(interaction-failure): clear interactions on any verify()

src/dsl/matchers.spec.ts, src/dsl/matchers.ts
Due to how javascript deals with 0 in if statements passing 0 into `integer()/decimal()` results in
the default value 13. This change corrects that by doing a nil check instead
=> fix(matchers): Allow integers/decimals to be 0

README.md
I tried to clarify the description of `providerStatesSetupUrl` a little since I had assumed that it's mandatory when provider states have been defined in the pact
=> updated explanation of providerStatesSetupUrl

src/pact.ts
Currently, `logLevel` is passed only downstream to pact-node and not respected by a local logger.
Steps to reproduce:
```
const path = require('path');
const { Pact } = require('@pact-foundation/pact');
const provider = new Pact({
port: 9999,
host: '0.0.0.0',
cors: true,
log: path.resolve(process.cwd(), 'pact.log'),
dir: path.resolve(process.cwd(), 'pacts'),
logLevel: 'fatal',
consumer: 'consumer',
provider: 'provider'
});
```
Expected: no logs in STDOUT
Actual: INFO logs in stdout.
This PR fixes the issue.
=> fix(logger): apply logLevel value passed via constructor

package.json
Including the current version of `pact-js` in a github project results in security warnings for contributors. (See [here](https://github.com/pact-foundation/pact-node/pull/131) for details).
This PR fixes those warnings by upgrading pact-node.
=> fix(vulnerabilities): upgrade version of pact-node

examples/graphql/consumer.spec.ts, examples/graphql/consumer.ts, src/dsl/apolloGraphql.spec.ts, src/dsl/apolloGraphql.ts, src/dsl/graphql.spec.ts, src/dsl/graphql.ts, src/dsl/matchers.ts, src/pact.ts
Separates the GraphQL Interaction interface into two, and sets reasonable defaults based on the discussion in #254 and #243. Changes: 
* Defaults `variables` and `operationName` to `undefined`
* Any `undefined` properties are not marshalled in interaction, but _falsey_ things will
* `GraphQLInteraction` - base class for GraphQL interactions (minor changes)
* `ApolloGraphQLInteraction` - tiny enhancement on the base class to default variables to `{}` and `operationName` to `null`, to match default behaviour (new)
@tomasAlabes @ngbrown how does this look to you?
=> feat(apollo-graphql): add Apollo specific GraphQL interface. 

src/dsl/matchers.spec.ts, src/dsl/matchers.ts
I was attempting to use the iso8601DateTimeWithMillis matcher on a field like `2018-11-21T14:44:31.537357Z`, which was being returned from a Go service, but the match was failing.
Currently, iso8601DateTimeWithMillis only allows the precision of the ISO8601 fractional seconds to 3 decimal places, this PR allows any number of decimal places.
I'm slightly unsure of this PR as the function is named `...WithMillis`, but this PR will allow precisions greater than a millisecond. I didn't want to break backwards compatibility, so renaming the function wasn't an option, but maybe it could live as a separate function like `iso8601DateTimeWithFractionalSecond`. Be interested to hear your thoughts.
=> iso8601DateTimeWithMillis: allow variable length fractional precision

examples/e2e/consumer.js, examples/e2e/test/consumer.spec.js, examples/typescript/test/get-dog.spec.ts, src/pact.spec.ts, src/pact.ts
- Pact.setup() now returns a PactOptionsComplete object,
containing the full configuration of the Pact provider
- Minor refactor of the setup() function to dynamically
load the port from the mock server
Fixes #259
=> feat(configuration): return configuration from setup()

README.md, examples/messages/README.md
These seem to date from before 6.0.0.
There are still some references to that branch in `.travis.yml` but I don't know what to do with them.
Also, I have not verified that every option in the fixed example README are still valid either, this is just the minimum changes I needed to apply to get my code to work.
=> docs(README): remove refs to old branch and syntax

src/dsl/matchers.spec.ts, src/dsl/matchers.ts
Currently, a value passed as an argument to `boolean()` matcher is ignored, and the value that is returned by mockserver is always `true`.
This PR to fixes this:
- `boolean()`, `boolean(true)` -> `true`
- `boolean(false)`, -> `false`
=> fix(matchers): remove hardcoded true value from a boolean matcher

src/pact-web.spec.ts, src/pact-web.ts
pact-web `provider.addInteraction` to accept `Interaction` as argument
relating to #270
=> feat: pact-web provider.addInteraction to allow Interaction instance

README.md, src/dsl/verifier.ts
=> add changeOrigin flag for http-proxy and update readme

src/dsl/verifier.ts
Currently, `providerStateSetupUrl` passed to `Verifier` constructor is always ignored, as `opts.providerStateSetupUrl` always overrides it. `providerStateSetupUrl` was deprecated in v8, but I still expect that it should to be possible to set it. 
This allows us to upgrade pact to v8 on our side without a full re-write of our custom provider state handling logic (as v7 is not maintained anymore).
This PR fixes described issue, so:
`providerStateSetupUrl` setting passed to Verifier constructor takes precedence over internal proxy server's `providerStateSetupUrl`.
=> fix(verifier): do not ignore providerStateSetupUrl passed to Verifier constructor 

CONTRIBUTING.md, README.md
Fixing some typos I found in the docs.
=> docs(readme): Fixes formatting of publishing options table in the docs

examples/graphql/mocha.opts, examples/typescript/test/mocha.opts, test/mocha.opts
Mocha Maintainance - removed deprecation warning (--compilers)
https://github.com/mochajs/mocha/wiki/compilers-deprecation
This is a was of [PR 339](https://github.com/pact-foundation/pact-js/pull/339) but PR399 currently fails on older node versions.
=> chore(config): TypeScript Example - mocha.opts removing --compilers since it is depreciated

README.md, examples/e2e/test/provider.spec.js, examples/graphql/provider.spec.ts
The examples & readme were giving we deprecation warnings (although they still worked) for their usage of `verifyProvider(opts)`.
This PR is simply updating the readme & the relevant examples to not show the warning anymore.
=> Address deprecation warnings for verifyProvider()

examples/typescript/package.json
When running the test for the typescript example, it is missing the Coverage statistics:
```
=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
```
This was due to missing a [nuc config section](https://www.npmjs.com/package/nyc#common-configuration-options) in the package.json
This is now fixed
```
=============================== Coverage summary ===============================
Statements   : 88.89% ( 48/54 )
Branches     : 100% ( 0/0 )
Functions    : 84.21% ( 16/19 )
Lines        : 88.24% ( 45/51 ) …
```
=> fix(example): Fixed missing coverage statistics by adding nyc section to package.json

.travis.yml, src/common/net.ts, src/dsl/verifier.ts
When the provider verification process is run against a remote provider, the origin
header can mismatch the actual remote proxied API.
This PR defaults to change the origin of the host header to the target URL in this case only, unless
specifically overridden by the user. This should remove a class of confusing issues
for new users.
See #280, #281 and #282 for background. This specific issue has come up on Slack
a number of times, and hence fixing before it appears as a GH issue.
=> Automatically set `changeOrigin: true` for non-local verifications 

src/dsl/graphql.ts
Issue:
I am using apollo client with http link. I am not adding any operation name in the query/mutation so operation name is passed as null in the payload.  
In the graph ql interaction, I can not pass operation name null as it only accepts string ( withOperation(operation: string): this;) while it is defined as  protected operation?: string | null;
Change: Can we allow operation name to accept null?
**Consumer:**
```
export function createTrust(): any {
return client
.mutate({
mutation: gql`
mutation {
createTrust {
id
}
}
`,
variables: {
Authorization: MOCK_AUTH_HEADER
}
})
.then((result: any) => result.data)
}
```
**Interaction:**
```
export const createTrustMutaion = new GraphQLInteraction()
.uponReceiving('a create trust request')
.withQuery(
`
mutation {
createTrust {
id
}
}
`
) …
```
=> fix(graph-ql): Allow withOperation to accept null

package-lock.json, package.json, src/dsl/verifier.ts
Removes duplicated VerifierOptions fixed in https://github.com/pact-foundation/pact-node/pull/178.
=> Remove need to duplicate `VerifierOptions`

src/common/net.spec.ts, src/common/net.ts
As discussed in issue #381, 
> We could warn if one of the interfaces is not available but others are, and fail if all promises reject (i.e. all checks fail).
---
The code that calls the `close` functions on the server instances used in testing isn't the cleanest approach - more than happy to take on feedback (which also applies to the whole PR).
=> fix(net): stop port check from failing due to ipv6 unavailability (#381)

examples/jest/__tests__/index.spec.js, examples/jest/__tests__/multipleSpecs.spec.js, examples/jest/pactTestWrapper.js, examples/jest/publish.js
Remove unnecessary done callbacks in async tests since Jest resolves the promises when they are
returned.
=> chore(examples): update Jest Example

src/dsl/matchers.ts
This is needed for `extractPayload` to work on objects with fields with `null` values.
=> fix(matcher): Update isMatcher to correctly check null values

examples/e2e/test/provider.spec.js
I was running these tests and noticed that when running the `npm run test:provider` the server was always empty and not able to create the data, this is because we need to importData() before running the server on the provider spec. Otherwise the server is going to be always empty.
=> fix: Need to initialise the data otherwise the server is going to load empty

README.md
Fixed example of Asynchronous API test to reference correctly named `MessageProviderPact` and remove reference to unused `Message`.
=> docs: correct asynchronous api examples

README.md, examples/e2e/test/consumer.spec.js, examples/e2e/test/publish.js, examples/graphql/publish.js, examples/jest/publish.js, examples/messages/publish.js, examples/serverless/publish.js, package.json, scripts/build.sh, src/dsl/publisher.spec.ts, src/dsl/publisher.ts, src/pact.ts
Creates a new interface that's a thin wrapper over `pact-node`, `Publisher`, that may be used to publish to the broker.
All examples and documentation now updated, to remove references to the project to avoid confusion.
=> feat: remove need for pact-node in almost all uses, including examples

src/dsl/matchers.spec.ts, src/dsl/matchers.ts
Fixes #454 by adding tests and changing the implementation of `extractPayload`.
=> fix(dsl): Fix extractPayload so that it passes through object properties that are not matchers (fixes #454)

src/dsl/interaction.spec.ts, src/dsl/interaction.ts
=> fix: allow matcher as the top-level value of a query string

src/dsl/matchers.spec.ts, src/dsl/matchers.ts
This reflects how it's defined by ISO 8601.
Unfortunately, I can only find third-party references. I got to this, because I had a validation problem between a Typescript consumer and a JVM producer (with this matcher, of course):
```
Expected "2020-12-10T09:01:29.06Z" to match '^d{4}-[01]d-[0-3]dT[0-2]d:[0-5]d:[0-5]d.d{3,}([+-][0-2]d(:?[0-5]d)?|Z)$'
```
=> fix: Expect at least one millisecond digit in iso8601DateTimeWithMillis

README.md
the V3 examples are not in the master branch yet, so the link need to be corrected
=> chore(docs): Correct link to XmlBuilder in V3 examples

README.md
the examples live inside the `/examples` folder, so correct the links
=> chore(docs): Correct links to karma examples

README.md
1. the correct link is https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors/
2. the sentence did not make any sense to me, so I've changed it (but I'm not native speaker, so feel free to correct me)
=> chore(docs): Correct links to to ConsumerVersionSelector documentation

.github/issue_template.md, .nycrc, README.md, src/common/logger.ts, src/dsl/verifier.ts, src/httpPact.ts
This should have been there since day 1. Response logging is a little more involved (it's a stream) but I'm still not sure it's really worth the effort of writing tests. I'd say the only value, is that the tests themselves are documentation for a feature (so perhaps they are).
In any case, it produces output that looks like this:
This should allow for a) much better bug reports if there are indeed issues and b) better debugging for users trying to work out what's going on.
FWIW I did look at tools like https://github.com/expressjs/morgan until I realised that the response body wasn't captured, and I needed another plugin for that. In the end, I decided that all of the hassle of an extra library wasn't worth it, and took inspiration from several sources on the best approach to stream the …
=> feat: request response tracing

examples/messages/package.json
those tests failed for me now several times with the 10sec timeout  see https://github.com/pact-foundation/pact-js/pull/578#issuecomment-762100126 so 20sec should make them more robust
=> fix: increase provider test timeout

examples/v3/e2e/consumer.js, examples/v3/e2e/test/consumer.spec.js, src/v3/pact.ts
if the body is already a string don't try to stringify it
fixes #577 
alternatively we could get rid of `JSON.stringify` all together, the limited e2e tests also pass then
=> fix: don't JSON.stringify body if its already a string

examples/v3/e2e/test/consumer.spec.js, examples/v3/e2e/test/provider.spec.js
1. the local pact file has an other path than given in the comment
2. fix the expected animal-id
the `.given()` function would set up animal with the id `100` but the test would query and expect id `1` back
it all worked when running all tests together because id `1` was setup earlier, but the test would fail when running only this test as consumer (`./node_modules/.bin/mocha test/consumer.spec.js --grep 'returns the animal'`) and then verifying the pact by the provider
=> fix: e2e test examples for V3

RELEASING.md
Updates the release docs with the new process.
Making a PR because I am committing from windows and don't want to accidentally stamp line endings or something.
=> docs(releasing): Update release docs with new process

examples/v3/e2e/consumer.js, examples/v3/e2e/provider.js, examples/v3/e2e/test/consumer.spec.js, src/v3/pact.ts
analog to https://github.com/pact-foundation/pact-js/pull/578 the response body does not need any stringify if its already a string otherwise an extra pair of quotes is added
```
AssertionError: expected '"id=100;first_name=Billy;last_name=Goat;animal=goat"' to equal 'id=100;first_name=Billy;last_name=Goat;animal=goat'
+ expected - actual
-"id=100;first_name=Billy;last_name=Goat;animal=goat"
+id=100;first_name=Billy;last_name=Goat;animal=goat
```
=> fix: don't strigify response that is already a string

examples/v3/e2e/test/provider.spec.js, examples/v3/e2e/test/publish.js, examples/v3/provider-state-injected/package.json, package-lock.json, package.json, scripts/ci/build-and-test.ps1
to fix the appveyor build on V3 branch:
1. don't expect a local brocker
for linux builds it started in https://github.com/pact-foundation/pact-js/blob/feat/v3.0.0/scripts/ci/build-and-test.sh#L42 but running on windows we cannot start Linux docker images
1. fix env. variables to use correct names from github actions and appveyor not travis
=> test: fix appveyor build on V3 branch

README.md
describing the `VerifierV3Options`
fixes  #608
=> chore: document VerifierV3Options

README.md
using `ignore-scripts` option of npm or yarn breaks the installation because the pact standalone binara cannot be downloaded
=> docs: ignore-scripts would break the installation

examples/v3/e2e/package-lock.json, examples/v3/e2e/test/helper.ts, examples/v3/e2e/test/publish.js
pact-node was renamed to pact-core (pact-js-core as GH repo) see https://github.com/pact-foundation/pact-js-core/pull/269
=> fix: rename pact-node to pact-core

src/v3/verifier.spec.ts, src/v3/verifier.ts
fixes #669
check if `this.config.pactUrls` is set at all before trying to run the `verify_provider`
=> fix: Error message with no pactBrokerUrl and no pactUrls

examples/v3/provider-state-injected/consumer/transaction-service.js, examples/v3/provider-state-injected/consumer/transaction-service.test.js, examples/v3/provider-state-injected/package-lock.json, examples/v3/provider-state-injected/package.json, examples/v3/provider-state-injected/provider/account-service.js, examples/v3/provider-state-injected/provider/account-service.test.js, native/index.node.d.ts, native/src/lib.rs, scripts/ci/build-and-test.ps1, scripts/ci/build-and-test.sh, src/v3/pact.ts, src/v3/xml/xmlBuilder.ts
same as #636 but rebased on `feat/v3.0.0` and with conflict solved
=> Fix/generators non json bodies - rebased

README.md, examples/v3/run-specific-verifications/.editorconfig, examples/v3/run-specific-verifications/.gitignore, examples/v3/run-specific-verifications/README.md, examples/v3/run-specific-verifications/filter-by-PACT_DESCRIPTION.json, examples/v3/run-specific-verifications/filter-by-PACT_PROVIDER_NO_STATE.json, examples/v3/run-specific-verifications/filter-by-PACT_PROVIDER_STATE.json, examples/v3/run-specific-verifications/package-lock.json, examples/v3/run-specific-verifications/package.json, examples/v3/run-specific-verifications/provider.js, examples/v3/run-specific-verifications/test/helper.ts, examples/v3/run-specific-verifications/test/mocha.opts, examples/v3/run-specific-verifications/test/provider.spec.js, native/src/verify.rs, scripts/ci/build-and-test.ps1
allow to run verifications for specific interaction description and/or state same as in the current version of Pact JS:  https://github.com/pact-foundation/pact-js#re-run-specific-verification-failures
I confess that I hacked this together without any knowledge of Rust just by staring at the code and googling, so any comment is appreciated
interaction filter if statements taken from https://github.com/pact-foundation/pact-reference/blob/dfd3ba973d22fc092061e8d905d0b4aeba65856b/rust/pact_verifier_ffi/src/verifier.rs#L97-L116 
fixes: #622 
ToDo:
=> feat: filter verification by description & state

src/v3/xml/xmlElement.spec.ts, src/v3/xml/xmlElement.ts
fixes #677 
there were two problems in the code
1. a typo in the variable name `context` vs `content` so the first `if` wasn't doing anything (introduced by https://github.com/pact-foundation/pact-js/commit/b3b5e6231e9f0ade7be045ff117b441d0169114a#diff-254dbea027a5c57e2b14fb8ff30edc28fea1d39ff2392d95731f7a16f60d5782R70)
2. the second `else if` compiled into the JS: `else if (content)`, so all cases that had any content were send down that road
now the whole section compiles into
```
if (typeof content === 'object' && content['pact:matcher:type']) {
this.children.push(new xmlText_1.XmlText(content.value || '', content));
}
else {
this.children.push(new xmlText_1.XmlText(content.toString()));
}
return this;
```
I deleted the fist if statement because it wasn't used in the first place and it …
=> fix: append text only works with Matchers

src/dsl/matchers.ts, src/dsl/message.ts, src/messageConsumerPact.ts, src/v3/xml/xmlElement.ts, src/v3/xml/xmlText.ts
Absolute imports can introduce problems for consumers which can be avoided using relative imports. Also relative imports align better with the general style used in pact-js
```
node_modules/@pact-foundation/pact/src/dsl/matchers.d.ts:6:25 - error TS2307: Cannot find module 'common/jsonTypes' or its corresponding type declarations.
6 import { AnyJson } from 'common/jsonTypes';
```
=> chore: avoid absolute imports

.istanbul.yml, .nycrc, README.md, examples/v3/e2e/test/provider.spec.js, examples/v3/provider-state-injected/consumer/transaction-service.js, examples/v3/provider-state-injected/consumer/transaction-service.test.js, examples/v3/provider-state-injected/provider/account-service.js, examples/v3/provider-state-injected/provider/account-service.test.js, examples/v3/todo-consumer/test/provider.spec.js, native/src/verify.rs, src/dsl/verifier/proxy/proxy.ts, src/dsl/verifier/proxy/stateHandler/setupStates.spec.ts, src/dsl/verifier/proxy/stateHandler/setupStates.ts, src/dsl/verifier/proxy/stateHandler/stateHandler.spec.ts, src/dsl/verifier/proxy/stateHandler/stateHandler.ts, src/dsl/verifier/proxy/tracer.ts, src/dsl/verifier/proxy/types.ts, src/dsl/verifier/verifier.spec.ts, src/v3/pact.ts, src/v3/verifier.spec.ts, src/v3/verifier.ts
The main changes:
* Replaces the rust callback which doesn't support promises for state handlers whilst preserving the function parameters `setup` and `params`. The response type now expects a Promise.
* Replaces the rust callback which doesn't support promises for request filters
* Updates to logging as I was debugging things
* Updates to types based on current best knowledge (I didn't feel like some of these types belonged in the proxy package, but also, they kind of needed to be there because of import cycles. Feedback welcome here).
Notably, the states (consumer) and state handlers (provider) now use the `JsonMap` type is outgoing/incoming. I think this is correct.
Opening as WIP for feedback, I'll squash it all before merging.
_EDIT_: check is failing due to code coverage. I can …
=> Native provider state handlers and request filters

examples/nestjs-consumer/test/app.spec.ts, examples/nestjs-provider/src/app.repository.ts, examples/nestjs-provider/test/pact/pact-provider-config-options.service.ts, examples/v3/e2e/test/consumer.spec.js, examples/v3/provider-state-injected/consumer/transaction-service.test.js, examples/v3/todo-consumer/test/consumer.spec.js, src/dsl/verifier/proxy/stateHandler/stateHandler.ts, src/dsl/verifier/proxy/tracer.ts, src/dsl/verifier/verifier.spec.ts, src/httpPact.spec.ts, src/messageProviderPact.spec.ts, src/v3/pact.ts, src/v3/verifier.ts
Wipes the internal state between test runs to enable re-use of the provider.
Not thread safe (it wasn't before), but if you want to run in parallel you can still create multiple providers as per what is currently the case, and the pact will be merged.
=> feat: reset consumer test state to enable re-use of PactV3 class

README.md, examples/e2e/test/provider.spec.js, examples/graphql/src/provider.spec.ts, examples/messages/provider/message-provider.spec.ts, examples/nestjs-provider/test/pact/pact-provider-config-options.service.ts, examples/serverless/provider/message-provider.spec.js
Also updates the tag values to use best practice examples.
=> docs: update readme and examples to use providerVersionTags and consumerVersionTags instead of tag (singular)

package.json
Current URL leads to a "Page Not Found" error.
Hopefully it updates the URL as shown in the screenshot of VS Code
=> chore(package): update homepage url

native/src/verify.rs
Fixes #713 
The consumerVersionTags, providerVersionTags and consumverVersionSelectors were overwritten with an empty array.
I hope you don't mind I used a formatter. Only changed code in `fn get_string_array` and `fn verify_provider`
=> fix: consumerVersionTags got overwritten with empty array

examples/nestjs-provider/test/pact/pact-provider-config-options.service.ts, src/v3/verifier.ts
Fixes vscode intellisense by using a relative import instead of an absolute one.
=> fix: using relative import for provider, fixes problems with intellisense in vscode

src/dsl/interaction.ts
Currently, it is allowed to write
```ts
willRespondWith: {
status: Matchers.like(200)
},
```
but the result will always be 500 as Matchers are not supported for the response status.
=> Fix interaction response status type

src/httpPact.spec.ts, src/httpPact.ts
This option can be used to monkey-patch the pact-mock-server. This addresses part of [issue #123](https://github.com/pact-foundation/pact-js/issues/123), which was originally closed due to the fact that option first had to be added to pact-node, which has since been done.
I am using jest-pact, and I want to be able to provide a monkeypatch, in order to increase the max URI length for the pact server, as it is [hard-coded to 2083 characters in WEBrick](https://github.com/ruby/webrick/blob/563b8309976065ba008430f2f1483d5bc3a713cf/lib/webrick/httprequest.rb#L446), but I want to increase that limit for my tests.
After this change, I can create a file webrick.rb
```rb
WEBrick::HTTPRequest.const_set('MAX_URI_LENGTH', 10000)
```
Then I can provide the monkeypatch option to jest-pact, to point to …
=> fix: All options are now passed down to pact-core in consumer pacts, allowing usage of the undocumented `monkeypatch` option

src/httpPact.ts, src/pact-web.ts
This PR throws an error in both pact-js and pact-web when a spec version other than 2 is used to create an http pact.
It's one way to fix #838 - the other, of course, would be to release the v3 compatibility.
=> fix: throw an error when pact spec version is not set to 2

README.md
update blog link(s) to docs.pact.io/blog
=> docs: update blog link

README.md
From slack discussion 
https://pact-foundation.slack.com/archives/C9VBGLUM9/p1652174044653219
installation instructions should advise to install in devDeps
=> docs: update README installation instructions

README.md
**related:** correct #865
`--save-dev` doesn't exists in yarn, so I updated the doc to use the [correct option `--dev`](https://classic.yarnpkg.com/en/docs/cli/add#toc-yarn-add-dev-d)
=> docs: correct yarn option to --dev

package-lock.json, package.json, src/dsl/verifier/proxy/parseBody.spec.ts, src/dsl/verifier/proxy/parseBody.ts, src/dsl/verifier/proxy/proxy.ts
This exposes body of the request in the verifier.requestFilter() allowing it to be manipulated prior to verifying the provider in the v3 beta
Picked up from @mefellows work on https://github.com/pact-foundation/pact-js/issues/304?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDUwMjc2MzIzMTo3Mjg0MDcw#issuecomment-1152416010 and is the same code as https://github.com/pact-foundation/pact-js/pull/873 abstracted out to follow the structure implemented in v3
=> feat: modify request body inside of verifier v3

src/dsl/message.ts, src/messageProviderPact.spec.ts, src/messageProviderPact.ts
This PR adds support for passing the params of providerStates to the `stateHandlers` of a `MessageProviderPact`.
=> fix: Add support for state params to MessageProviderPact (#372)

examples/v3/e2e/test/consumer.spec.js
This fixes some tests. There are more issues in these tests, but for now fixing two issues:
- name tests and interactions
(so that separate interactions are created)
- fix expected result for x-www-form-urlencoded data request
(it only sends limited data, so it should only expect that as result)
=> chore: fix create mate tests

src/httpPact/index.ts
Fix an issue where TS is looking for a module named `dsl/mockService` and fails to find it. By making the path relative it stops complaining.
=> chore: reference source file by relative path

package-lock.json
Warning when running `npm i` on a clone of pact-js master branch
```
❯ npm i
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
```
I assume this should have the fix-up applied and committed, to avoid it repeating every time it is installed now
=> chore: npm old lockfile warning - update to 2.0

src/dsl/verifier/proxy/types.ts
Resolves https://github.com/pact-foundation/jest-pact/runs/7642886870?check_suite_focus=true#step:4:128
```
Error: node_modules/@pact-foundation/pact/src/dsl/verifier/proxy/types.d.ts(1,8): error TS1259: Module '"/Users/runner/work/jest-pact/jest-pact/node_modules/@types/express/index"' can only be default-imported using the 'esModuleInterop' flag
```
import could also change to `import { RequestHandler } from 'express';` as that is the only import used in the file
https://github.com/pact-foundation/pact-js/blob/60fa69f139e65000edcd28b1487bf372f338a59d/src/dsl/verifier/proxy/types.ts#L47
=> fix: dsl/verifier - express import typescript error

docs/migrations/9-10.md
This PR corrects the migration guide with some information about changes to the provider verifier, following feedback from Adam Witko on slack: https://pact-foundation.slack.com/archives/C9VBGLUM9/p1660227998292199
=> docs(migration): Correct migration guide

docs/migrations/9-10.md, src/v3/matchers.spec.ts, src/v3/matchers.ts
The function is called `reify` in 10.x, and aliased as `extractPayload`
for backwards compatibility.
[Slack discussion](https://pact-foundation.slack.com/archives/C5F4KFKR8/p1660042113955029) for context.
=> feat: port extractPayload function from 9.x

package.json
When preparing #946 I noticed that the `docs` folder was deleted following `npm run dist`. This is because they're deleted in the `clean` step - but, I don't see the docs being autogenerated anywhere.
My guess is that `docs` was left around from a previous iteration, and now that there is a docs folder again, it's not supposed to be removed by the build script.
=> build: No longer remove docs folder in clean step

src/v3/matchers.spec.ts, src/v3/matchers.ts
isMatcher inadvertantly passes when a field name is 'value'
If you've made many commits that don't adhere to this style, we recommend squashing 
your commits …
=> fix reify logic relating to isMatcher function

src/dsl/graphql.spec.ts, src/dsl/graphql.ts
Fixes pact generated with graphql with double "Content-Type" headers
The example at pact-js/examples/graphql when running npm run test:consumer it generates a Pact file with two “Content-Type” headers. Notice how one is in lower case “c” in “content”
```
{
"consumer": {
"name": "GraphQLConsumer"
},
"interactions": [
{
"description": "a hello request",
"request": {
"body": {
"operationName": "HelloQuery",
"query": "\n          query HelloQuery {\n            hello\n          }\n        ",
"variables": {
"foo": "bar"
}
},
"headers": {
"Content-Type": "application/json",
"content-type": "application/json"
},
```
=> Fix double content type header graphql

src/index.ts
While looking at https://github.com/pact-foundation/nestjs-pact/pull/17  , I noticed that one of the breaking changes in V10 was that `VerifierOptions` is now deeply imported. This PR fixes that by exporting it at the root again.
=> fix: Export `VerifierOptions` as a root export

scripts/ci/build-and-test.sh, scripts/install-plugins.sh
This PR:
* Improves the logging for when install-plugins fails
* Ensures that windows actually fails when install-plugins fails
It exposes the problem with install-plugins, which is that it is being rate limited by github. You could fiddle about with a token to fix this, but probably it would be better to do one of:
* Pin the version, avoiding the need for the call (easiest)
* Replace the API call with https://github.com/marketplace/actions/github-api-request
* Remove the need for a plugin cli step entirely by using a package manager (imo, best)
=> build: Improve logging in install-plugins script

docs/troubleshooting.md
The PR adds a workaround on how to install `pact-js` using a base image `node:18-alpine` for example.
It might be helpful when you use Alpine for production build and you want just install the dependencies without actual pact tests execution.
=> docs: Add a note for Alpine + Docker

src/dsl/matchers.spec.ts, src/httpPact/ffi.ts, src/v3/ffi.ts, src/v3/matchers.spec.ts, src/v3/matchers.ts, src/v3/types.ts, src/v3/xml/xmlElement.spec.ts, src/v3/xml/xmlElement.ts, src/v3/xml/xmlText.ts
This fixes #1054 by widening the type so that the V3 matchers no longer need to be called with something that can be assigned to `AnyTemplate`. Since this is a widening of the type, it is not a breaking change.
I also removed all references to `AnyTemplate` and added tsdoc so that it is deprecated. It's still exported, but just not used anywhere. It can be removed in a future major release.
While I was there, I refactored the types out of matchers.ts into `types.ts`  for readability. These are now re-exported by `matchers.ts` so that any (inappropriate) deep links will still work, and anyone importing the type from `MatchersV3.Matcher` will still work.
I also added a TODO comment that in some future release we'll need to rename the `interfaces` that have the same names in the V2 and V3 …
=> chore: Improve types

src/dsl/message.ts, src/dsl/options.ts
In #882 the `StateHandlers` type was changed so that it was incompatible with the other `StateHandlers` type, resulting in conflicts when Typescript merged the two. This caused problems where it was impossible to correctly type `StateHandlers` (see  #1057). 
This PR is a breaking change that simply renames the message `StateHandlers` interface to `MessageStateHandlers`, and therefore fixes #1057.
Probably the better fix would be to introduce a breaking change that makes both types the same again - but I didn't want to get in to untangling what is supposed to happen.
This must not be squash merged, otherwise you won't get the breaking change in the changelog.
=> chore: Rename message's `StateHandlers` to `MessageStateHandlers`

src/dsl/matchers.ts
The current implementation of the `uuid` matcher function has a param name that does not match the JSDoc param. Although this doesn't cause any bugs, it may be good to update this for consistency.
This PR renames the JSDoc param from `uuuid` to `id` to reflect the name of the param
=> chore: Rename `uuid` matcher JSDocs param

examples/e2e/package-lock.json, examples/e2e/package.json, examples/graphql/package-lock.json, examples/graphql/package.json, examples/jest/package-lock.json, examples/jest/package.json, examples/messages/package-lock.json, examples/messages/package.json, examples/mocha/package-lock.json, examples/serverless/package-lock.json, examples/serverless/package.json, examples/typescript/package-lock.json, examples/v3/e2e/package-lock.json, examples/v3/e2e/package.json, examples/v3/provider-state-injected/package-lock.json, examples/v3/run-specific-verifications/package-lock.json, examples/v3/run-specific-verifications/package.json, examples/v3/todo-consumer/package-lock.json, examples/v3/typescript/package-lock.json, examples/v4/plugins/package-lock.json, examples/v4/plugins/package.json, package-lock.json, package.json
Picks up https://github.com/pact-foundation/pact-js-core/pull/432 via 13.13.5 of `pact-js-core`
- side note, I imagine CI which is flakey which we should fix when we get time
- side side note, can we use dependabot to trigger these updates automatically to save a user manually doing it (if not I might script up quickly updating these values and running npm install in each of the respective folders)
=> chore: pact-js-core 13.13.5

.github/workflows/build-and-test.yml, .github/workflows/publish-9x.yml, .github/workflows/publish.yml
This PR bumps the github checkout action to v3 to avoid the deprecation warnings in the build logs
=> ci: Update github checkout action to v3 to avoid deprecation warnings

docs/matching.md, docs/provider.md, examples/e2e/README.md, examples/e2e/test/provider.spec.js, examples/serverless/README.md
This PR improves the distinction between Pact and PactFlow in the documentation by including the some of the changes I suggested on slack.
It also accidentally reformats the code examples in the docs - but since this happened automatically because my editor picked up the settings used in the rest of the code, I left it in (as it is a consistency improvement).
=> docs: Improve distinction between Pact and PactFlow

examples/messages/README.md
Fixed the link to the `Message` object in the messages examples README was incorrect.
Please note: to test this PR, I ran the following commands:
```sh
npm install
```
```sh
npm run dist
```
This resulted in an error:
So I ran this command:
```sh
ENABLE_FEATURE_V4=true npm run dist
```
And that command succeeded.
=> docs: fix Message link in messages examples README

MIGRATION.md, README.md, docs/troubleshooting.md
add notes on v12 migration
- no requirement for node-gyp build change (still relevant for v10/v11)
- node 16+ required
=> docs: add notes on v12 migration/troubleshotting

examples/mocha/test/get-dogs.spec.js, src/httpPact/ffi.ts
This PR reverts the change added in #1031. Multi-valued headers are supported partially, as they must be specified using the array syntax. The open issues have connected and reproduced upstream issues now, but I think we should release this sooner rather than later.
=> fix: do not split headers by comma

src/messageConsumerPact.ts
This PR fixes the merge parameter for the call to writePactFile() in MessageConsumerPact. The change matches the code for the same call from the Http Pact.
=> fix: MessageConsumerPact merge pact file correctly

CONTRIBUTING.md
I noticed a typo in the CONTRIBUTING.md file, which needed correction. Additionally, I observed that the majority of the lines in the file ended with dots, while a minority did not. To maintain consistency and standardize the formatting, I made the adjustment by adding dots to the end of lines where they were missing.
=> [DOCS] Fix typos in CONTRIBUTING.md

docs/consumer.md
If you've made many commits that don't adhere to this style, we recommend squashing 
your commits to a new branch before making a PR. Alternatively, we can do …
=> fix(docs): Fix typo in test statement

scripts/ci/test-examples.sh, src/dsl/message.ts, src/messageConsumerPact.ts, src/v4/message/index.ts, src/v4/message/types.ts, src/v4/types.ts
This change removes the remaining `AnyTemplate` references from previous parts of the code base, excluding the original HTTP DSL (as this is old and stable, and most users would be using `PactV3` or greater).
It is a widening of the types, so is technically backwards compatible on method inputs, however some exported types may be used outside of Pact and the widening from `AnyTemplate` to `unknown` might require type casting (as `unknown` is not iterable, for instance). This is preferable to the current situation however, which is breaking the message pact interface (#1133) and also - as described in #1061 - misleading.
=> Fix/issue 1133 remove `AnyTemplate`

.github/workflows/build-and-test.yml, .github/workflows/publish.yml, src/v4/index.ts
V4 interface has been experimental for long enough that it is now a de-facto API. Removing the feature flag.
Documentation updates to follow.
=> feat: remove feature flag for v4

examples/v4/plugins/provider.ts, examples/v4/plugins/test/matt.consumer.spec.ts, scripts/install-plugins.sh, src/pact.integration.spec.ts
Fix for https://github.com/pact-foundation/pact-reference/issues/366
Plugin PR's raised here
- https://github.com/mefellows/pact-matt-plugin/pull/1
- https://github.com/mefellows/pact-matt-plugin/pull/2
Once above are merged, will want the plugin download location reverting back to the source [mefellows](https://github.com/mefellows/pact-matt-plugin) repo over my fork
=> fix: revert test workaround / update to matt plugin 0.1.0

package-lock.json, package.json, src/dsl/graphql.ts, src/dsl/interaction.ts
Mentioned in issue #1169, `lodash.omitby` will be reported security risk by BlackDuck. This PR retired `lodash.omitby` dependency and replaced it with `ramda` to avoid vulnerability.
`lodash.omitby` is used to filter out null and undefined value from a object. `ramda` does not provide same name `omitBy` function but this functionality could be achieved by `ramda.reject` referring to [link](https://github.com/ramda/ramda/issues/2084).
=> fix: retire lodash omitby to fix vulnerability

.github/workflows/build-and-test.yml, examples/messages/consumer/message-consumer.spec.ts, examples/messages/package-lock.json, package-lock.json, package.json, scripts/ci/build-and-test.sh, src/dsl/matchers.ts, src/dsl/message.ts, src/messageConsumerPact.ts, src/v4/message/index.ts
Metadata _values_ always had their matchers stripped off. Once the matchers (integration JSON) were able to be passed in, we needed to update the core (https://github.com/pact-foundation/pact-js-core/pull/493) to use the latest metadata FFI method, which allowed this structure to be passed in.
Fixes #1133
Fixes #745
=> chore: allow v3 matchers in message metadata

package-lock.json, package.json, src/dsl/verifier/proxy/parseBody.spec.ts, src/dsl/verifier/proxy/parseBody.ts, src/dsl/verifier/proxy/proxy.ts, src/dsl/verifier/proxy/proxyRequest.spec.ts, src/dsl/verifier/proxy/proxyRequest.ts
Add native support of HTTPS_PROXY and HTTP_PROXY for verifier for #1188 
This change adds two pieces of behavior:
- The verifier's 2 step parse body behavior now uses a proxy request buffer (instead of the 'proxyReq' rewrite behavior) to ensure the request stream is accessible for intermediary agent behavior
- The verifier natively supports HTTP_PROXY/HTTPS_PROXY config and assigns a proxy http Agent where those values are present
This results in out-of-the-box support for corporate proxies in the js verifier
=> feat(corporate proxy #1188): support in verifier

src/v3/types.ts
In reviewing the query DSL, we are only allowing matching on `string` values or matchers that work on strings.
However, the matching capability actually does extend to checking the types of query parameters, even if their underlying representation in is a string.
This change allows both `boolean` and `number` types to be used in matching rules.
In a future change, we should also support the ability to have empty and no values (as per https://github.com/pact-foundation/pact-reference/pull/411).
=> feat: support matching numbers, bool in query strings

src/dsl/verifier/proxy/hooks.spec.ts, src/dsl/verifier/proxy/hooks.ts, src/dsl/verifier/proxy/proxy.ts
Current behaviour will run the `beforeEach` and `afterEach` hooks multiple times if there are several provider states defined in an interaction. This is due to the way the hook are run on every call to `/_pactSetup` via the proxy.
This change will ensure each of those hooks is run only once per interaction, regardless of how many provider states are defined in that interaction.
---
Our primary use case in applying this fix was to be able to support multiple `given()` statements in our consumer tests without having them each trigger the `beforeEach` hook (which we want to use for resetting state), eg
```js
await provider()
.addInteraction()
.given("has a pet with status", "sold")
.given("has a pet with status", "pending")
.uponReceiving("a request for pets with multiple statuses")
...
``` …
=> fix: allow hooks to run only once per interaction

.github/renovate.json
To ensure broader compatibility, dependencies of Pact JS should keep using a broad range of versions, with only dev dependencies being pinned to ensure a consistent developer environment.
Ref: https://docs.renovatebot.com/presets-default/#pinonlydevdependencies
=> chore: pin only dev dependencies

CHANGELOG.md, MIGRATION.md, README.md, RELEASING.md, examples/e2e/test/consumer.spec.js, examples/v3/provider-state-injected/provider/account-repository.js, src/dsl/apolloGraphql.spec.ts, src/dsl/interaction.ts, src/messageConsumerPact.ts, src/messageProviderPact.spec.ts, src/messageProviderPact.ts, src/v3/matchers.ts, src/v4/http/types.ts
=> chore: fix typos

.github/workflows/test.yml
arm64 runners now available, so lets use them to speed up our CI runs
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
the test-arm64 workflow only tested alpine, so the glibc case was not covered.
the test-alpine workflow, using containers as a first class concept in gh actions, unfortunately do not support arm64 yet
```
JavaScript Actions in Alpine containers are only supported on x64 Linux runners. Detected Linux Arm64
```
so this PR 
1. removes qemu on test-arm64 workflows
2. replaces ubuntu-latest (x64) runner with ubuntu-24.04-latest (arm64) runner
3. tests glibc case by running the `npm ci && npm test` workflow on the native ubuntu-24.04-latest (arm64) runner
4. tests musl case by running the existing …
=> ci: use arm runners for arm64 workflows

CHANGELOG.md, examples/jest/package-lock.json, examples/jest/package.json, package-lock.json, package.json
correcting changelog & version which failed to update in the last release.
relates to #1372 
can't push straight to master (neither can CI on release), due to restriction of test completion check.
CI is impacted, as release workflow is kicked off manually, and does not trigger the test workflow, and therefore completion check. 
the release workflow itself, does perform tests prior to release, so maybe these need to be hooked up to the test completion check 🤷🏾‍♂️
=> chore(release): 14.0.0

docs/troubleshooting.md
Users on windows must install a minimum set of tools alongside nodejs installations, in order to use pact-js.
This can either be done via the official nodejs installer, with the `Tools for Native Modules` option checked, or manually by following the [instructions on node-gyps readme](https://github.com/nodejs/node-gyp?tab=readme-ov-file#on-windows) 
fixes https://github.com/pact-foundation/pact-js-core/issues/608
=> docs: update windows troubleshooting information

README.md
This PR just updates the `npm i` command in the `README`.
- switches to longhand `install`
- removes `-S` (short for `--save`) which has been the default for a long time and is no longer necessary
- adds `--save-dev` (because the vast majority of the time, pact is used as dev-time, not as a production dependency)
- removes `@latest` which is redundant and unnecessary
```diff
-npm i -S @pact-foundation/pact@latest
+npm install --save-dev @pact-foundation/pact
```
=> docs: update npm install command

docs/provider.md
This PR makes a couple small changes to the [Provider Verification docs](https://docs.pact.io/implementation_guides/javascript/docs/provider#api-with-provider-states) – specifically the *API with Provider States* `stateHandlers` example code
This fixes two issues:
1) there was a missing comma, so the example was technically broken
2) `[null]:` as a property key doesn't work in TypeScript. This updates it to work in JS *and* TS
```diff
const opts = {
...
stateHandlers: {
-    [null]: () => {
+    "null": () => {
// This is the "default" state handler, when no state is given
-    }
+    },
"Has no animals": () => {
animalRepository.clear()
return Promise.resolve(`Animals removed from the db`)
```
When this code is used with TS, it raises the following error:
> `A computed property name must …
=> docs: fix provider stateHandlers example
