README.md
Fixes example in README so that it can be copy/pasted and run.
=> fix(readme): fix example in readme

examples/mocha/test/index.spec.js
I was getting just timeout instead of a description of what was going wrong. This helped me debug.
=> Better error handling in the example in case something goes wrong

src/pact-web.js, src/pact.js
As per title.
Fixes #33 for us.
=> Wait for removeInteractions() on verify()

.gitignore
Updating `.gitignore` for IntelliJ IDEA files
=> fix(gitignore): ignore IDE generated project files

README.md, examples/ava/index.js, examples/ava/package.json, examples/ava/test/index.spec.js
* Adds a small example project that makes use of the popular AVA test framework
* Updates README with a link to it alongside Jest and Mocha.
=> feat(example): adding example for the AVA test framework

README.md
In response to our discussion on gitter with @mefellows and @bethesque about how the verify method works.
=> docs(verify): better describe the verify method

karma/jasmine/client.js
I noticed this when I reviewed the code.
=> Remove a dirty hack and propose better solution.

examples/ava/test/index.spec.js
Refactored for proper testing conventions with Pact.js:
* Interactions should be specified and setup in each test case
* Verifying the interaction in each test and clearing out all interactions
=> docs(ava): refactor ava test to reflect proper testing conventions

.gitignore, examples/jest/README.md, examples/jest/__tests__/another.spec.js, examples/jest/__tests__/index.spec.js, examples/jest/index.js, examples/jest/package.json, examples/jest/pactSetup.js, examples/jest/pactTestWrapper.js, examples/jest/publish.js
I could probably add some docs to why this is so? And some other tips (like running pact tests as a separate task so that you can run normal unit tests concurrently)
=> Added jest multiple pact test files example

examples/e2e/README.md
The run instructions where missing some steps to get the e2e example to run.
=> add missing steps

examples/jest/__tests__/index.spec.js
=> Remove unused imports

README.md
- Added a comment for clarification about Pact version 
- Update code example with async call to use the callback pattern so it properly waits until completion
=> docs(README): update code example

README.md
Some of the rows said `false`, while their description said `Required`.
=> docs(readme): Fix required column in publish opts

README.md
Just a tiny typo fix I noticed while reading through the docs.
=> De-duplicating link to Typescript example.

package-lock.json, package.json
To address https://github.com/pact-foundation/pact-js/issues/287
=> fix(pact-node): Upgrade to @pact-foundation/pact-node@^8.1.1

README.md
I spent a lot of time attempting to integrate pact with an Angular project and wanted to share where I lost a lot of time so others wouldn't have to.
I'm not sure if you accept pull requests like this, but I thought I'd put it up just in case. :)
=> chore(docs): add note on Angular to troubleshooting section in README

README.md, src/dsl/matchers.spec.ts, src/dsl/matchers.ts
=> feat(matching): add string type matcher

src/messageProviderPact.ts
=> fix(MessageProvider): Shut down test environment even if message provider throws an error

package-lock.json, package.json
=> Update version of graphql package

README.md
The code was invalid due to some issues with parenthesis.
=> docs: fix code example in readme

src/dsl/matchers.ts
https://github.com/pact-foundation/pact-js/issues/433
=> #433: changing regex for ISO8601 Dateformat to be more flexible

examples/e2e/test/publish.js, examples/graphql/publish.js, examples/jest/publish.js, examples/messages/publish.js, examples/serverless/publish.js
Show best practice for consumer versions and tags.
=> docs: update example publishing scripts

src/v3/pact.ts
Not 100% sure that everything is covered, but it should be a bit more complete now.
=> Attempt to improve PactV3 type definitions

examples/jest/__tests__/index.spec.js
=> fix: typos

src/common/request.ts, src/dsl/interaction.spec.ts
=> feat: allow also WebDAV HTTP Requests

src/common/request.ts, src/dsl/interaction.spec.ts
fixes https://github.com/pact-foundation/pact-js/issues/518
=> feat: allow WebDav REPORT request

src/common/request.ts
Targeted master, as  not sure where to target, so suspect you'll be change that
=> UPDATED | Added Popsicle maxBufferSize setting

.github/pull_request_template.md
just a small fix of the md formatting, to make the checkboxes being displayed nicely
visual diff:
=> docs(pr-template): correct checkbox formatting

examples/v3/e2e/consumer.js, examples/v3/e2e/package-lock.json, examples/v3/e2e/test/consumer.spec.js
Tests for #589 
This is specially to check the correct encoding in the query parameters
=> test: check encoded query parameters

examples/v3/provider-state-injected/consumer/transaction-service.js, examples/v3/provider-state-injected/consumer/transaction-service.test.js, examples/v3/provider-state-injected/provider/account-service.js, examples/v3/provider-state-injected/provider/account-service.test.js
If you've made many commits that don't adhere to this style, we recommend squashing 
your commits to a new branch before making a PR. Alternatively, we can do …
=> test: MatchersV3.fromProviderState on body

src/v3/pact.ts
=> Lviana menlosecurity patch 2

README.md
Update an examples with path dependency
=> fix: update an examples with path dependency

README.md, examples/e2e/package.json, examples/graphql/package.json, examples/jest/package.json, examples/messages/package.json, examples/nestjs-consumer/package.json, examples/serverless/package.json, package-lock.json
This fixes #777. I'm doing it via a PR to see if it fixes the issues we had with PR builds.
=> Use --auto-detect-version-properties instead of --tag-with-git-branch

src/dsl/verifier.ts
=> fix: verifier req/res logging on debug

CODE_OF_CONDUCT.md
=> docs: update pact-support@googlegroups.com to pact-foundation

package-lock.json, package.json, src/dsl/verifier.spec.ts, src/dsl/verifier.ts
This exposes body of the request in the verifier.requestFilter() allowing it to be manipulated prior to verifying the provider
Picked up from @mefellows work on [issue 304](https://github.com/pact-foundation/pact-js/issues/304?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDUwMjc2MzIzMTo3Mjg0MDcw#issuecomment-1152416010 )
=> feat: modify request body inside of verifer

src/httpPact/index.ts
Addresses https://github.com/pact-foundation/jest-pact/pull/214#issuecomment-1205206648
=> fix: import clc from cli-colour

src/v3/pact.ts
See repro here: https://github.com/lennartquerter/pact-v3-test
=> fix: PactV4 error handling logic

package-lock.json, src/v3/matchers.ts
Fixes #945 
I also updated package-lock, since no current version of node uses the old package-lock format.
=> fix: Fix issue where MatchersV3.string() with no arguments would not correctly match strings

src/v3/ffi.ts, src/v3/types.ts, src/v4/http/index.ts
=> fix: support multiple header values with matchers

src/v3/matchers.spec.ts, src/v3/matchers.ts
If you've made many commits that don't adhere to this style, we recommend squashing 
your commits to a new branch before making a PR. Alternatively, we can do …
=> fix: missing min in v3 eachLike pact-foundation/pact-js#958

docs/matching.md
Current link points to a 404 page not found, I've updated the link to point at the correct page.
=> chore: update from provider state link

examples/v4/plugins/package-lock.json, examples/v4/plugins/package.json, examples/v4/plugins/provider.ts
workaround for https://github.com/pact-foundation/pact-reference/issues/366
=> fix(ci): update matt plugin provider test

README.md
RE: Really minor change that may help a noob (like me) understand the test better. 
If you've made many commits that don't adhere to this style, we recommend …
=> chore: update misspelling in docs example test

src/v3/matchers.spec.ts, src/v3/matchers.ts
=> fix: nullValue matcher does not reify

src/common/request.spec.ts, src/dsl/graphql.spec.ts, src/dsl/interaction.spec.ts, src/dsl/matchers.spec.ts, src/dsl/verifier/proxy/stateHandler/setupStates.spec.ts, src/httpPact/ffi.spec.ts, src/messageConsumerPact.spec.ts, src/messageProviderPact.spec.ts, src/v3/matchers.spec.ts, src/v3/xml/xmlElement.spec.ts
A few minor style/linting fixes
EDIT: fixing the lints uncovered other issues, which I thought I could fix in this PR, but opted not to (hence the many forced pushes below).
=> style: fix lints
